version: "3.8"

services:
  app:
    build: .
    container_name: analytic_tool
    restart: always
    ports:
      - "59547:80"
    volumes:
      - /home/guest/analytic-tool:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ci3_db
      POSTGRES_USER: ci3_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
